aside exercise
ReCoded-Org/bootcamp-iraq-2020apr-1-css-1-excercise pull request #1
Opened 2020-04-22 17:22 UTC by shna-rafeeq

2020-04-23 09:14 UTC, MohammedAlabd requested changes
That's really cool that you are the first who made the PR good job 👏 

you have to work more on styling to fix some bugs 

![image](https://user-images.githubusercontent.com/55356198/80081633-e2b12600-855b-11ea-901f-e27750c81558.png)

and work more on your code indentation

2020-04-23 09:14 UTC, MohammedAlabd commented on mahmud-shna/style.css
> +
don't leave new line here 

put it after the closing of curly brackets

2020-04-23 09:14 UTC, MohammedAlabd commented on mahmud-shna/style.css
> +body {
Don't try to use the tag selectors, always use class instead because class are reusable and easy to control

2020-04-23 09:14 UTC, MohammedAlabd commented on mahmud-shna/style.css
> +    height: 210vh;
why you are using 210vh ?

I think you can use **%** instead

2020-04-23 09:14 UTC, MohammedAlabd commented on mahmud-shna/style.css
> +  aside h3 , aside p{
always use classes

2020-04-23 09:14 UTC, MohammedAlabd commented on mahmud-shna/style.css
> +
don't leave a lot of empty lines

2020-04-25 09:41 UTC, MohammedAlabd requested changes
It looks amazing Good job :partying_face: 
there is only one comment below fix it and every thing will be perfect

2020-04-25 09:41 UTC, MohammedAlabd commented on mahmud-shna/index.html
> +              </table>
this table is actually a  navbar and you should put it into footer tag outside the main tag

2020-04-25 10:16 UTC, shna-rafeeq commented
Thank you so much for your comments
I made the change 🤗

On Sat, Apr 25, 2020, 12:41 PM Mohammed Alabd <notifications@github.com>
wrote:

> *@MohammedAlabd* requested changes on this pull request.
>
> It looks amazing Good job 🥳
> there is only one comment below fix it and every thing will be perfect
> ------------------------------
>
> In mahmud-shna/index.html
> <https://github.com/ReCoded-Org/bootcamp-iraq-2020apr-1-css-1-excercise/pull/1#discussion_r415025498>
> :
>
> > +        <h2>Photos from that time when I never visited these places</h2>
>
> +        <img class="avatar" src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSNOLKDnOoq6ja8XiRk9JDxsPUNn9klNU6nU9clMPZFcJk76t0H&usqp=CAU"alt="avatar">
>
> +        <p class="clear">By<a class="slink" href="#"> Not Salah Al-Dhafteri</a> under <span id="s3span">Not visited places</span>
>
> +          <div class="ldiv">
>
> +            <img id="f2img1" src="https://i2-prod.mirror.co.uk/incoming/article5445553.ece/ALTERNATES/s1200b/0_Florida.jpg" alt="img1">
>
> +            <img id="f2img2" alt="img2"src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMSERUSEhIVFhMXGBUVGRUXFhcbFxgYGh4YFx0YFhgYHyggGBomGxobITEhJSkrLi4uFx8zODUsNygtLisBCgoKDg0OGhAQGy0lICUtLi0tKy0tLy0vLy4tKy8vLS0vLS0tLS0tLS8tLy8tMC0tLS0tLS0vLS0tLS0tLy0tLf/AABEIAKgBLAMBIgACEQEDEQH/xAAcAAAABwEBAAAAAAAAAAAAAAABAgMEBQYHAAj/xABFEAACAQIEAwYCBwYEBAYDAAABAhEAAwQSITEFQVEGEyJhcYEykQcUQlKhscEjYoKS0fAzcrLhFSSi8RYlQ1NjgzTC0v/EABoBAAIDAQEAAAAAAAAAAAAAAAIEAQMFAAb/xAA1EQACAQIEAwYFAwMFAAAAAAABAgADEQQSITFBUWETIqGxwfBxgZHR4QUjMiQzohRSYnLx/9oADAMBAAIRAxEAPwDLKECle7opWvVWmVmnCjTRKNNGDIMMDRgaTFHFEDBIh66KLNdNFeDacaBKOKEV068KRRDSjGk4qDJECK6KNFdlqLSbwsVwoStdlqJ0ELStlPENY1GvTz0oLYpddNaO2kAtYweJYYJcZRMeY166+dM2t08Dm4A7bsqk/ICiPbqqkL01J5CE72cjrGJWhUUs6UnFTa0IG8CuigZaFajjOnV1GzUFdYToRlomWl4ouWhKSQ0SigK0o1FmgIG0IGJFaIy05y0RkqpqcINGxFBFLFaCKoKyzNCqDSwoqmjTVqWEAmFKCiFKVoprmAnAx2WopNKthzSfdGnCplAIgV0UcJRWrraSbwBXTQxQFK7WdpAzUaaDu66K7WdpDBqNNJijiiBkEQCaCa40WoJkiGDUcNSdCK4NIIik11ABRgK7NBh0FHfRSegNAoqydn+ytzFBHZYw7XFtlpgt1VBv7+tVV64p02Y8pNKmalQKJXODX1yDMNEOvmsk/lp7U6ugSY25elWji/0dFL144a5bFkKrG1ccq4Vo0zNpvIEkGonjtm1ba2tq2yDurRYMxaWIkkE6gRG/SlsDixUIQcvWW4zCtTux5yGe1SDpTt6I9vSeVaZAiisY0K0kVp0VorUBW8tDRtlo7DbzH+1HyTNAtuVP7vijyMAn5xVZ0lg1hBQsaLNFZq4tpItCuaG2k7DmB86ACnmFXQnmCp+QY/nFVgEmHpG9EY06S3oT/egJ/T8aJYw5JH69ZAH/AFEVLaSFF41uJG+/SkYpe8ZM8uXpSJFKPvLQYE0daTilWEQo35+vT22+dCDJtBBotcxrqLNBkrmoM1Fiuy1qXidhOZqSIo+Q0Pd0JuYQIEIDSitRTarghrrkTtDDsJpNrdOGt7HqPxGn+/vXFaK14N7Rtkpa3a8BPmPwgf8A7UOQU9wa+Exy/wD6tUBW0NGuZF5KDJTy/YjKOZB+eZl/SpXtFwy3aIFtdJy5pJDFQA3p4p+VCWAYLzhhGKluXrK8UpfB4bO0bAaknYDqf72Bo4tCTOw19hoB+QqWtYburYEeN9SegEQPSSD6Bq5tJyDNGN22qgjkD7zttrryHSGOtM9/9qd3bRdxbQEkfiefyA38iedEu4coxVokdNR6g8wRrQi20ioTa4Gk7D4YvMcgTsTty0rQewGEvvg78Ei2j23UsxCgw+YrEkH4NqqHBbzr3mQx+zYnTpsR5iatHY/FjILQJBKXc2phvHaZARtoA/pJ60li8xVl4aeV5fgbCqh4/m3rJLB2A11jfY3QSCwDlpHMNPxExznlVK7U8Tt375a1bVUUC2gUGCqyAxB+0R5ADQRzq94h1sW79/u1dkyEBhpmbwAnqASDHOOVZVeQxPLr/e1U4BALvbp78I3+rPZxTHxMIbvWj270eYO4/vnTcmd/n/WgJitUPzmVl4iLXhB3kHUHqKRalbPi8J9R6/0P9KTipveSRbaBbOUg9PlT6zhxJK7QCJ+63I+hkH0NMSaf8ObYHlM+aNofk0H3ahbpLaR11kXeSCR/cUlUjxLDQT1BPy/vU/5qZ2bBYwN4Y+sAk/gDVLaQiNbQgp5giTmAH2SfkD/X8KbNahQ3WR7iD+RFT/ZfAMy3n1Udy2VoMHxKCNPegNUKLwkplmtI3BpO+2unWSgH50peEW/UCT1Jkn/Wv8tKYJPCRpIDfMFTv7UrjxAA82f8zHp8I9qt3F4OwkFctwY586TK04KyfOutYVnbKgLEAkxsANST0FLvYayFudo3t6Gemv8AT8Yoo5n+5P8AZpe5bKiDuT+A0H5n5UXujlmNJ38+lVw4iqzoKd2sMxGiqR1PP08qPgsPoXOg2kb/AMPUmYHrSt3DifHM6aKNFHJdun50QWEBBihoTXVp3iF4IoZotdXXgw4tk7Cf76Utb1WY+HQ+an+h/MUja30MHl09KeWLoVsxHgbw3B0nSY6jcf71BMtQRC7bgEe49Nj+MCk+6OTPyzZT1BiRPrrH+U08xNgqIOu4nl0E+sAj0NL8HwLXsNisokIiXt9jbMSR07t7mvlQvUyi/wAIYpXa3QyFNSnB7RZX9iemjKf6U1xeEy93kJYOIkx8YMMo/A+jCpHs+h1H3gR75rf9KguCLiFTQq1jC4a3nxNlerpPoXkn/qq2dtMFbFhbpgOSSgjXQl2PoenlyqG7O2YutcMFVGXeNYzSD1hKt3brDD/h6F1hrdtBOkBmCjKP+rSs7EVbYhBNKhT/AKdzz9Jm/BsMblxEAksw/Db8T+FTPH2VGbLBywisNJbcnXYAliOUGlOxlnIt6+R8Cd2h00uPudfug/jNI4QhrrXWEpZU3ADrmc6WkPWWgnrDdaZepdieA8/ekURLUwOJ9/mD2e4YwtXXCg3TNtQ3ICBcaDtAMa9DULZwTu5RFLMATpyC777R/tWqcI4C7YZUI1Kgs3OfjJb7RLPJ9T5VUcThVw1y9aUAsUFvMNRLaxmBnYEkgGcu06BKliyzPbfh5S/EYQKiDgN/ORXCLQy3D1tXQJj7rEHUeXKKt3AeAG0lzELLA20KMzKLXiUcxJJUETG5B25R/COGXrmS4qFrZcgkMoByqdCCdyT50+bA3CFtggpbm2sgEGAFll1mSPKQedLYmsWqMo4W8tYxgqFgG97w923dxNm9ZW7hma7kCoLhUyrK3hzaNIEcqzzFWHtuyEQ6kqy8wQYII561fU4ZctsrrbQspBGW2MwIM5gFUGdBqB15RUNxjg9tnS5n7t2t3r7q7GWZCNAXPxN4v5dtasweIyXVvjA/UcMXYVB8N5WE7t9GGU9VH4xzHlv+gXuHEEDeRKkbMP3Tz9NxSmOCi66zBDEBpBkjqV035j/elMHjIJt3BNskSvNW++nRvTetVSCAZm8cp+si2EaUa62YZuezevI+/wCYPWpfiHDp2MkjMjDa6vlH2wN158vODzZTB22Pp/etSWkZCN494TgxeLW9Q5Um2eRca5D/AJgCB5x1onDrwDAEb6fPQg+RGnyqR7E2y2L7rNlLoVVhGjAq6OAdGhlDegJpHtNgTbu95ly5mdXUbJfQ+NV6KZV1HS4BypYYj90oZf2P7QccN494rYDKjfaEqTzYjb3KkfMVBo3d3FeJAIaORAOo9DBHpU9w9++tRPiOn8Q1X5iR7VCYpP6j30I9iKYYXFoDm1mEuGJ4QEFovlKo6W2kgFhbdbauTHOxfsn+GpXjWD+rWjbS3GVRabUFTDE6E6Gd9NZbUa1LDh4v8MV7TD/BQywBaba92STzaO7BPVPSprtJgRdw+I8OYtkur5llSI25pPvXnTVOcX56/WbSr3TbiPfpMRwHwmPMD3IFLcQcMCQdIn2MN+JA/mFdhLRt5gQQVYgg7gqy6H3pHHeER5KvtAP6CvQj+Mwi2kYroCfYe+/4ae9WXhuAbD4G7iLix3sIuviycyNNiSPkKhOHYM3r1qyASXZRpvBOp/l19q1LiXCj9WFxlLLaQQFAhi22gA0Ej2rNxlUKVTnHcDSzBn5DSZLhMK166tobmFnkANST5DU064mJcWrbAoJEg6QNc59gZ6Qfe4YLgi4WzdxAZC5DgFp2HhJUEQR3hAnTafWr4RdTeaPFqdNiNYI6fa/hXqaOk/bPpsJD0jSSx3PlBfLZQGNRsDyPMn0nbqwHWIk2y/iM/h+vOnF9zdeNlHXlEmSfIST5k9amuE9kWxNsXe+WypJCK4aWUbPp1M/KrqtZKYux0la02qGyiQ1BFHihy1oXmZeJkU/wOB71MoBV5hHjwO3/ALTNsrn7J66HeQzIqR4RxRrDCNUMq6NJRlPVf18garqZsvd3ltErms20ccQ4AyWBdUFoBzkAxAMEkHVGXYqeWo5xH2CDrO8Buo5A+euk+YrXOC2LWJtG9Y8TZf2tsn4/snMOZgZCeYKtuBWW9ouFnCYgqJNtvEk7m2ZGVv3lIKnzU0nhcUXJRtxH8TQFOzrt71jzCJntkcwRbYdJ0B/mC+xPWnH0dYkW8ebTibd5WtOvUNpr5AEn2pnwO+DdyHa4uX1YfCfU6fKi3MR9Xxtu9EglXPQyYYekhhV9Zc1Nl6QabAMrdZYu1XZ5rVm0yoP+Wa0rt96f2OaOf+CpP+eoPC2il26IIy3bwHTRlGnoVNa12xwzPhMSFOlxLhX+FWugD1b9azviYAvmDIPfsPT6xe0g882b5CkMDiCwsev3jdekBqOkL2bwwYMsHxOgkcg4e2Pxb8Kvf0kELhFXdXcuwiZRJfXTQQoHvVX+j2xmuLImbtqNtMmd9fLQHT71WD6TLuaLUTOW2NT5XbkgcsoUe9UYg3xQ6S6mLUgOhlGxINrC2cOAZYd445l3E89/ASnsKlcBwvvL9nB24YAriL51gspy7HqZMHlUfaxJbEBjH7IGAdBKjNB8swEVoXYLh4s4d8bcWHv/ALSCNVQDwL6c/SKsxVQonXf5n7SqkAWuPgPgPv8AeH7V49cHh+7t/wCIwgDnrpI13kj51kfFLvdmzJJd3ZyfIDLPrLHX92NCKuPG7xxN9rzvCjMLQOsiIZjroNo6+4o2Fw6Ym1bzW1/ZG4mbINYykBzzbxHfz966a9jQzcTvDZTXrBLw3YXEqMNIJzi4xYaZSY8BGvTSYER8+4mMl5QzSGacoPwmCYM+x15MKguPcTtYFLWRP8UuTkYhZUhTmAnxD229KZ2OMd+6XY+JwYJ1Gi7fI0ozPUdnIsN/ER2iFo5aYNzt4Ey3NiyAjDQswSJjQag/h15mortXxY3cVdVQALFhrGeJLFyCRrP70ehp0zq9q3HJx+RNRXEUtlOIgC62K71siqBlbMSq67+EyTtpVlG3eY8vMyP1MHMijiT4CU7hjNfYOUN7MuZ4nNA0ZlA1kQeRo/E8BkC3EYvYYlVuRsRujxsw36EajyNw/geNsWO9Nm4gtuIuKRpngRKkwc3XfOatWD4W95cxUZmXNctDLF1S2WSinw3JX4hGuU6HRnlxIRVN+lvh7+8yf9OWLLbXf39vpK3w3Ghh3V06EyrTGV+RnkZ+0P8AutibImXQHdXEAb/aT7pkT5EHcEy4x3Z/7VgnbMEMtK6zl01jSVOonrK0lwu+Lo7thFxQRB5jpPPy/WFhtaqVRpByMhs0UTgTL3dzD3Yu2/GrCf2lvN4Ltv8AeBOQoftCOdXjt1wE4hTdXVb9pHUjb6zaBIH/ANlssAeq68hVZ4FfRD3LwGzzaYzlDEN4WgyFf4T55dyJrUuH4fv8PcwzEqfsk7o/xAjyBE/zcstZOJqPTqC/DjHqdNChI+YmEcIYhgNidVPXWAR/EIn+lLcXteMkbNDj0bcezfrU12lwzAMxABtXjI+5ngXUgfZz5W/+31prjrWe0twbgwR5Npr08YGn71bNCqKi3mXXpFO7Lx9GOLFzh72W3tXHGm+S4J/1SdPu1cMHP1NJiVRAZ1EjQjXzFZf9FmLy4m7ZJ0u2yV/zp4hHsW+Vasln9iwA3VtPOdfea89j1yV2HPX385r4Jw1BehtMV7QJOKxOh+NomNfFaAOnWf8AtUDxb4oHVvwgVa+1IIx14Ez4UP8A1WdPwqtX1/bqDsCWPoGZif5RW/Ra9EHoPKZGIH7hHU+csH0X8MNziWaNLKudesd2PzJ9q1TtNaNxhZDFQdSQTM6gbaHmdfu+sVb6EsF+xv3j8TXFWfJRO/q1WXtfje4w9zEZcxWSNNY2E+Wp22msDGsXrkD4D38Zq4IBaYJ6n38pQe3V5BbWzZIhSFb7xgb85UyBIPPXyp3FLuS2EG51Pz/Ugn0UdaeXmNy5LeGFlj0mXJ9QpPuoqOvXAWa6w8I2X/SnpoJ8kPWtrDUexo9TEcRW7WobRXgXCu+uLZOgI7y60gZbY8QSTsWMH+X7pq5X+JFz+xVVtKMi5rUyF0kRsOUeVRXAMO4Q2UBN6+wNx4kqswdR5kab6tvsL9huyTKoC3dPLwz5xGv9jlWPi6oZ9fl95o4RMiafP7epmN0NdFdXqJ5WARRSKUigIqJ15oP0dtctW+9w7q5OY3bLmIC/aU7bbg9ZmrL9IHZ0Y7B9/ZH7W2C4XmRAzoepgAjzA61kvCMdds3A1lirmVEGPi8P61uHZHjJupldMjrC3EOkOY2H3G5EaTI6Vh4xHo1RVHv3tN3C1ErUeztsLe/OYLgbkMDzBBH+35fxVLdq7OZVuDbN+DiQB6EH+epP6SOz4weLz2x+yvEuv7p0zL7E7eYolq13+DdftKpA9iGH4hB7n20lqhlDjYxRUIzUzuJp/BsX9Z4VZuFpJtqrHzjumHzH41nDuGxLE7ZXP817ENt+HtVp+i/F95w27ZnVJZR0jxf6ln+IVXMTZC3zB07tpHSLt1vyYVlYeyV3X4zUYF6Qb3qJO/ROku20qwJ66W7YH+o/jQ9q8ctzGEz4bSvc2 [...]

2020-04-26 07:55 UTC, MohammedAlabd commented
that's really cool
 
I love it

LGTM

2020-04-26 07:56 UTC, merged